"""add global_risk to pedagogical_feedback

Revision ID: 464576e87da1
Revises: 71573c2a8cb3
Create Date: 2026-06-13 18:38:21.433433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464576e87da1'
down_revision: Union[str, Sequence[str], None] = '71573c2a8cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedagogical_feedbacks', sa.Column('global_risk', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedagogical_feedbacks', 'global_risk')
    # ### end Alembic commands ###
