"""create ocorrencias table

Revision ID: 50489374deb2
Revises: ddb44b2eb3a0
Create Date: 2026-01-12 15:23:25.955951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '50489374deb2'
down_revision: Union[str, Sequence[str], None] = 'ddb44b2eb3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = set(inspector.get_table_names())

    if 'audit_logs' not in tables:
        op.create_table(
            'audit_logs',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('tenant_id', sa.Integer(), nullable=True),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('target_type', sa.String(length=50), nullable=False),
            sa.Column('target_id', sa.String(length=50), nullable=True),
            sa.Column('details', sa.JSON(), nullable=True),
            sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['usuarios.id']),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'comunicados' not in tables:
        op.create_table(
            'comunicados',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('titulo', sa.String(length=200), nullable=False),
            sa.Column('conteudo', sa.Text(), nullable=False),
            sa.Column('data_envio', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column('autor_id', sa.Integer(), nullable=True),
            sa.Column('target_type', sa.String(length=50), nullable=False, server_default='TODOS'),
            sa.Column('target_value', sa.String(length=100), nullable=True),
            sa.Column('arquivado', sa.Boolean(), nullable=False, server_default='false'),
            sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id']),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'ocorrencias' not in tables:
        op.create_table(
            'ocorrencias',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('tipo', sa.String(length=50), nullable=False),
            sa.Column('descricao', sa.Text(), nullable=False),
            sa.Column('observacao_pais', sa.Text(), nullable=True),
            sa.Column('gravidade', sa.String(length=20), nullable=False, server_default='LEVE'),
            sa.Column('acao_tomada', sa.Text(), nullable=True),
            sa.Column('data_ocorrencia', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
            sa.Column('aluno_id', sa.Integer(), nullable=False),
            sa.Column('autor_id', sa.Integer(), nullable=True),
            sa.Column('resolvida', sa.Boolean(), nullable=False, server_default='false'),
            sa.Column('notificacao_status', sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id']),
            sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id']),
            sa.PrimaryKeyConstraint('id'),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas', 'total',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre3',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre2',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre1',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_table('ocorrencias')
    op.drop_table('comunicados')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
