"""create ocorrencias table

Revision ID: 50489374deb2
Revises: ddb44b2eb3a0
Create Date: 2026-01-12 15:23:25.955951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50489374deb2'
down_revision: Union[str, Sequence[str], None] = 'ddb44b2eb3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('audit_logs', ...) - Already exists
    # op.create_table('comunicados', ...) - Already exists
    # op.create_table('ocorrencias', ...) - Already created in partial run
    # op.alter_column('notas', 'trimestre1', ...) - Skipped for SQLite compatibility
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas', 'total',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre3',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre2',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('notas', 'trimestre1',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.drop_table('ocorrencias')
    op.drop_table('comunicados')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
