"""add_pedagogical_feedback

Revision ID: 71573c2a8cb3
Revises: 851d36622ca1
Create Date: 2026-06-13 18:24:34.165555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71573c2a8cb3'
down_revision: Union[str, Sequence[str], None] = '851d36622ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedagogical_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('metas', sa.JSON(), nullable=False),
    sa.Column('acoes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('feedback_usuario', sa.Text(), nullable=True),
    sa.Column('acoes_finais', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ped_feedback_aluno', 'pedagogical_feedbacks', ['aluno_id'], unique=False)
    op.create_index('idx_ped_feedback_tenant_year', 'pedagogical_feedbacks', ['tenant_id', 'academic_year_id'], unique=False)
    op.create_index(op.f('ix_pedagogical_feedbacks_academic_year_id'), 'pedagogical_feedbacks', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_pedagogical_feedbacks_tenant_id'), 'pedagogical_feedbacks', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_aluno_archived'), table_name='alunos')
    op.drop_index(op.f('ix_notas_aluno_disciplina'), table_name='notas')
    op.drop_constraint(op.f('stripe_webhook_events_event_id_key'), 'stripe_webhook_events', type_='unique')
    op.drop_index(op.f('idx_usuario_archived'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_usuario_archived'), 'usuarios', ['tenant_id', 'is_archived'], unique=False)
    op.create_unique_constraint(op.f('stripe_webhook_events_event_id_key'), 'stripe_webhook_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notas_aluno_disciplina'), 'notas', ['aluno_id', 'disciplina_normalizada'], unique=False)
    op.create_index(op.f('idx_aluno_archived'), 'alunos', ['tenant_id', 'is_archived'], unique=False)
    op.drop_index(op.f('ix_pedagogical_feedbacks_tenant_id'), table_name='pedagogical_feedbacks')
    op.drop_index(op.f('ix_pedagogical_feedbacks_academic_year_id'), table_name='pedagogical_feedbacks')
    op.drop_index('idx_ped_feedback_tenant_year', table_name='pedagogical_feedbacks')
    op.drop_index('idx_ped_feedback_aluno', table_name='pedagogical_feedbacks')
    op.drop_table('pedagogical_feedbacks')
    # ### end Alembic commands ###
