"""create_usuario_turma

Revision ID: 851d36622ca1
Revises: n8o9p0q1r2s3
Create Date: 2026-06-12 09:58:44.977717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851d36622ca1'
down_revision: Union[str, Sequence[str], None] = 'n8o9p0q1r2s3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('turma', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'academic_year_id', 'usuario_id', 'turma', name='uq_usuario_turma')
    )
    op.create_index(op.f('ix_usuario_turmas_academic_year_id'), 'usuario_turmas', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_usuario_turmas_tenant_id'), 'usuario_turmas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_turmas_tenant_id'), table_name='usuario_turmas')
    op.drop_index(op.f('ix_usuario_turmas_academic_year_id'), table_name='usuario_turmas')
    op.drop_table('usuario_turmas')
    # ### end Alembic commands ###
