"""add_matricula_to_usuarios_and_fk_ondelete

Revision ID: bfcf63671ffb
Revises: c34d973ff7b1
Create Date: 2026-04-28 11:41:01.654856

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'bfcf63671ffb'
down_revision: Union[str, Sequence[str], None] = 'c34d973ff7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_fk_for_columns(table_name: str, constrained_columns: list[str]) -> None:
    inspector = inspect(op.get_bind())
    target = set(constrained_columns)
    for fk in inspector.get_foreign_keys(table_name):
        if set(fk.get("constrained_columns", [])) == target and fk.get("name"):
            op.drop_constraint(fk["name"], table_name, type_="foreignkey")
            return


def upgrade() -> None:
    """Upgrade schema."""
    # Add matricula to usuarios for cross-year user identity (may already exist if added via direct SQL)
    op.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS matricula VARCHAR(32)")
    op.execute("""
        UPDATE usuarios u SET matricula = a.matricula
        FROM alunos a WHERE u.aluno_id = a.id AND u.matricula IS NULL
    """)

    _drop_fk_for_columns('academic_years', ['tenant_id'])
    op.create_foreign_key('fk_academic_years_tenant_id_restrict', 'academic_years', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    _drop_fk_for_columns('alunos', ['tenant_id'])
    _drop_fk_for_columns('alunos', ['academic_year_id'])
    op.create_foreign_key('fk_alunos_tenant_id_restrict', 'alunos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_alunos_academic_year_id_restrict', 'alunos', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')

    _drop_fk_for_columns('audit_logs', ['user_id'])
    _drop_fk_for_columns('audit_logs', ['tenant_id'])
    op.create_foreign_key('fk_audit_logs_tenant_id_set_null', 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_logs_user_id_set_null', 'audit_logs', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')

    _drop_fk_for_columns('comunicados', ['tenant_id'])
    _drop_fk_for_columns('comunicados', ['academic_year_id'])
    op.create_foreign_key('fk_comunicados_tenant_id_restrict', 'comunicados', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_comunicados_academic_year_id_restrict', 'comunicados', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')

    _drop_fk_for_columns('notas', ['academic_year_id'])
    _drop_fk_for_columns('notas', ['tenant_id'])
    op.create_foreign_key('fk_notas_academic_year_id_restrict', 'notas', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_notas_tenant_id_restrict', 'notas', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    _drop_fk_for_columns('ocorrencias', ['academic_year_id'])
    _drop_fk_for_columns('ocorrencias', ['tenant_id'])
    op.create_foreign_key('fk_ocorrencias_academic_year_id_restrict', 'ocorrencias', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_ocorrencias_tenant_id_restrict', 'ocorrencias', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocorrencias', type_='foreignkey')
    op.drop_constraint(None, 'ocorrencias', type_='foreignkey')
    op.create_foreign_key(op.f('ocorrencias_tenant_id_fkey'), 'ocorrencias', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('ocorrencias_academic_year_id_fkey'), 'ocorrencias', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.create_foreign_key(op.f('notas_tenant_id_fkey'), 'notas', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('notas_academic_year_id_fkey'), 'notas', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_constraint(None, 'comunicados', type_='foreignkey')
    op.drop_constraint(None, 'comunicados', type_='foreignkey')
    op.create_foreign_key(op.f('comunicados_academic_year_id_fkey'), 'comunicados', 'academic_years', ['academic_year_id'], ['id'])
    op.create_foreign_key(op.f('comunicados_tenant_id_fkey'), 'comunicados', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'usuarios', ['user_id'], ['id'])
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.create_foreign_key(op.f('alunos_academic_year_id_fkey'), 'alunos', 'academic_years', ['academic_year_id'], ['id'])
    op.create_foreign_key(op.f('alunos_tenant_id_fkey'), 'alunos', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.create_foreign_key(op.f('academic_years_tenant_id_fkey'), 'academic_years', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
