"""add_matricula_to_usuarios_and_fk_ondelete

Revision ID: bfcf63671ffb
Revises: c34d973ff7b1
Create Date: 2026-04-28 11:41:01.654856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcf63671ffb'
down_revision: Union[str, Sequence[str], None] = 'c34d973ff7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add matricula to usuarios for cross-year user identity (may already exist if added via direct SQL)
    op.execute("ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS matricula VARCHAR(32)")
    op.execute("""
        UPDATE usuarios u SET matricula = a.matricula
        FROM alunos a WHERE u.aluno_id = a.id AND u.matricula IS NULL
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('academic_years_tenant_id_fkey'), 'academic_years', type_='foreignkey')
    op.create_foreign_key(None, 'academic_years', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('alunos_tenant_id_fkey'), 'alunos', type_='foreignkey')
    op.drop_constraint(op.f('alunos_academic_year_id_fkey'), 'alunos', type_='foreignkey')
    op.create_foreign_key(None, 'alunos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'alunos', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('comunicados_tenant_id_fkey'), 'comunicados', type_='foreignkey')
    op.drop_constraint(op.f('comunicados_academic_year_id_fkey'), 'comunicados', type_='foreignkey')
    op.create_foreign_key(None, 'comunicados', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'comunicados', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('notas_academic_year_id_fkey'), 'notas', type_='foreignkey')
    op.drop_constraint(op.f('notas_tenant_id_fkey'), 'notas', type_='foreignkey')
    op.create_foreign_key(None, 'notas', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'notas', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('ocorrencias_academic_year_id_fkey'), 'ocorrencias', type_='foreignkey')
    op.drop_constraint(op.f('ocorrencias_tenant_id_fkey'), 'ocorrencias', type_='foreignkey')
    op.create_foreign_key(None, 'ocorrencias', 'academic_years', ['academic_year_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'ocorrencias', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ocorrencias', type_='foreignkey')
    op.drop_constraint(None, 'ocorrencias', type_='foreignkey')
    op.create_foreign_key(op.f('ocorrencias_tenant_id_fkey'), 'ocorrencias', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('ocorrencias_academic_year_id_fkey'), 'ocorrencias', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.create_foreign_key(op.f('notas_tenant_id_fkey'), 'notas', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('notas_academic_year_id_fkey'), 'notas', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_constraint(None, 'comunicados', type_='foreignkey')
    op.drop_constraint(None, 'comunicados', type_='foreignkey')
    op.create_foreign_key(op.f('comunicados_academic_year_id_fkey'), 'comunicados', 'academic_years', ['academic_year_id'], ['id'])
    op.create_foreign_key(op.f('comunicados_tenant_id_fkey'), 'comunicados', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'usuarios', ['user_id'], ['id'])
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.create_foreign_key(op.f('alunos_academic_year_id_fkey'), 'alunos', 'academic_years', ['academic_year_id'], ['id'])
    op.create_foreign_key(op.f('alunos_tenant_id_fkey'), 'alunos', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.create_foreign_key(op.f('academic_years_tenant_id_fkey'), 'academic_years', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
