"""fix comunicado_leitura data_leitura default and comunicado autor nullable

Revision ID: c34d973ff7b1
Revises: f09657161e43
Create Date: 2026-04-25 03:57:46.083484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34d973ff7b1'
down_revision: Union[str, Sequence[str], None] = 'f09657161e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comunicados', 'autor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('comunicados_autor_id_fkey'), 'comunicados', type_='foreignkey')
    op.create_foreign_key(None, 'comunicados', 'usuarios', ['autor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comunicados', type_='foreignkey')
    op.create_foreign_key(op.f('comunicados_autor_id_fkey'), 'comunicados', 'usuarios', ['autor_id'], ['id'])
    op.alter_column('comunicados', 'autor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
