"""Initial migration

Revision ID: ddb44b2eb3a0
Revises: 
Create Date: 2025-12-16 20:08:27.355025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb44b2eb3a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('turma', sa.String(length=32), nullable=False),
    sa.Column('turno', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=80), nullable=False),
    sa.Column('disciplina_normalizada', sa.String(length=80), nullable=False),
    sa.Column('trimestre1', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('trimestre2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('trimestre3', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('notas')
    op.drop_table('alunos')
    # ### end Alembic commands ###
